<?php
    include ("./Celular.php");
    $obj = new Celular("iPhone 6", "Apple", "12", "16", "8", "1300");
    echo $obj ->getNome();
    echo " ";
    echo $obj ->getMarca();
    echo " ";
    echo $obj ->getTam_tela();
    echo " ";
    echo $obj ->getMemo_arm();
    echo " ";
    echo $obj ->getMemo_ram();
    echo " ";
    echo $obj ->getPreço();
    echo "<br />";
    $obj2 = new Celular("Galaxy S7", "Samsung", "12", "16", "8", "1300");
    echo $obj2 ->getNome();
    echo " ";
    echo $obj2 ->getMarca();
    echo " ";
    echo $obj2 ->getTam_tela();
    echo " ";
    echo $obj2 ->getMemo_arm();
    echo " ";
    echo $obj2 ->getMemo_ram();
    echo " ";
    echo $obj2 ->getPreço();
    echo "<br />";
    $obj3 = new Celular("Moto X", "Motorola", "12", "16", "8", "1300");
    echo $obj3 ->getNome();
    echo " ";
    echo $obj3 ->getMarca();
    echo " ";
    echo $obj3 ->getTam_tela();
    echo " ";
    echo $obj3 ->getMemo_arm();
    echo " ";
    echo $obj3 ->getMemo_ram();
    echo " ";
    echo $obj3 ->getPreço();
    echo " ";
?>
